



IMPLICIT_ARG1_DICT = "implicit_args/dict/"
IMPLICIT_ARG1_DICT_CURR_PRODUCTION_RULE = IMPLICIT_ARG1_DICT + "curr_production_rule.txt"
IMPLICIT_ARG1_DICT_PREV_CURR_PRODUCTION_RULE = IMPLICIT_ARG1_DICT + "prev_curr_production_rule.txt"
IMPLICIT_ARG1_DICT_PREV_CURR_CP_PRODUCTION_RULE = IMPLICIT_ARG1_DICT + "prev_curr_CP_production_rule.txt"
IMPLICIT_ARG1_DICT_CURR_NEXT_CP_PRODUCTION_RULE = IMPLICIT_ARG1_DICT + "curr_next_CP_production_rule.txt"